### ISSUE TITLE
"Wrong number of values for server_name. Expected 1, but got 2."

### ISSUE THREAD

**Issue by chris-martin** [ishchenko/idea-nginx#21]
For the first example at http://nginx.org/en/docs/http/server_names.html

```
server {
    listen       80;
    server_name  example.org  www.example.org;
}
```

The syntax highlighter reports an error:

> Wrong number of values for server_name. Expected 1, but got 2.

Versions:
* idea-nginx 0.0.15
* IntelliJ 13.1.4

**Comment by danielsun174** [comment]
Push. Still not working correctly.
