### ISSUE TITLE
Unable to install with Phpstorm EAP version 145.256.26

### ISSUE THREAD

**Issue by tkn98** [ishchenko/idea-nginx#37]
When browsing the repository within the settings dialog it's just asked to install and restart but after restart the plugin disappeared.

I then downloaded the file manually and could with the install from disk operation at least provoke an error message:

> ![error_042](https://cloud.githubusercontent.com/assets/10513307/13775129/2530e0fe-eaa3-11e5-9693-04b8f6fe5963.png)

> Fail to load plugin descriptor from file idea-nginx.zip

I assume this is due to changes in EAP but I don't know. Just wanted to report the issue first.

Download obtained via: https://plugins.jetbrains.com/plugin/4415?pr=idea
ZIP downloaded from: https://plugins.jetbrains.com/plugin/download?pr=idea&updateId=22578

**Comment by jon-peterson** [comment]
I am seeing this also with Intellij 15.0.4.

**Comment by tkn98** [comment]
The [workaround](https://github.com/ishchenko/idea-nginx/issues/37#issuecomment-197027790) did work for me as well.

**Comment by ishchenko** [comment]
Should be closed in #41
