### ISSUE TITLE
Plugin does not run under IntelliJ IDEA 2016.1, Build #IU-145.258

### ISSUE THREAD

**Issue by khaliddermoumi** [ishchenko/idea-nginx#38]
The plugin does not run under the mentioned IDEA version.
It cannot be installed too, except by extracting the jar from the zip. But even when the jar is installed by "from disk", it does not run. It does not recognize nginx.conf files, no menu entries are created, etc.

It would be wonderful if this very useful plugin would be running again under the new version!

This is the IDEA release that was tested:
IntelliJ IDEA 2016.1
Build #IU-145.258, built on March 17, 2016
JRE: 1.8.0_76-release-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by jiangnanrusheng** [comment]
+1

**Comment by qianzhangsheng** [comment]
+1

**Comment by kreutter** [comment]
+1 (IntelliJ IDEA 15.0.5)

**Comment by benbor** [comment]
I have the same issue.
My environment is
IntelliJ IDEA 2016.1
Build #IU-145.258, built on March 17, 2016
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

**Comment by honzahommer** [comment]
+1

PhpStorm 2016.1
Build #PS-145.258, built on March 16, 2016
JRE: 1.8.0_76-release-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
