### ISSUE TITLE
Ubuntu 14.04 PyCharm Syntax Highlighting Not Working

### ISSUE THREAD

**Issue by nicorellius** [ishchenko/idea-nginx#39]
I downloaded the ZIP, unzipped it, and then went to **PyCharm > Settings > Plugins > Install plugin from disk...** I then restarted PyCharm a few times, and the `*.conf` file is not syntax highlighted. I read in the docs that syntax highlighting is supported, but that also:

> Configuration files are not displayed in project view, but can be opened with ctrl+shift+n (go to file) shortcut. Neighbour configuration files can also be opened with "go to file". All files in configuration file's directory are available for "go to file" and are treated as nginx configuration files. Child directories are also scanned (1 level only), thus some default configuration locations can be opened (e.g. /etc/nginx/nginx.conf and some stuff in /etc/nginx/sites-available).

Not sure if this means that files open in PyCharm from the Project view will not be syntax highlighted. In my opinion, if I have a repo with deployment scripts, conf templates, etc, these should be highlighted when viewed.

Any ideas what I'm doing wrong?

**Comment by dblado** [comment]
this should fix your problem: https://github.com/ishchenko/idea-nginx/issues/22

**Comment by nicorellius** [comment]
Thanks
