### ISSUE TITLE
Поддержка http-push-stream

### ISSUE THREAD

**Issue by syabro** [ishchenko/idea-nginx#47]
Привет. Спасибо за отличный плагин.

Подскажи почему директивы сабжа подсвечиваются как неизвестные?

![](http://s.syabro.com/9d0t7.png)

**Comment by ishchenko** [comment]
Автодополнение и документация генерируются по исходникам. Кажется, это тут https://github.com/ishchenko/idea-nginx/blob/master/src/net/ishchenko/idea/nginx/KeywordsFromSourcesGenerator.java Автокомплит сторонних модулей надо подключать руками, pull requests are welcome
