### ISSUE TITLE
map block shows Unknown variable

### ISSUE THREAD

**Issue by MrPostie** [ishchenko/idea-nginx#49]
When creating a map block in a Nginx configuration, the message pops up that the variable is unknown, although the Nginx syntax configuration is OK.
![nginx-phpstorm](https://cloud.githubusercontent.com/assets/10062082/16682248/c9d1ce38-44f9-11e6-90d9-8cf285825fd6.jpg)

**Comment by slavafomin** [comment]
The issue is still present in `0.1.9`.
