### ISSUE TITLE
clash with rainbow brackets causes crash

### ISSUE THREAD

**Issue by polaroidkidd** [ishchenko/idea-nginx#71]
Unfortunately the plugins crashes when used in conjunction with rainbow-brackets.

I've opened an issue [here](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/254#issuecomment-538608351) and maybe the bug originates here. 

Is there a known work-around for this by chance?

**Comment by Deadleg** [comment]
This should be fixed from https://github.com/ishchenko/idea-nginx/commit/79ead4e04b84515bee3e4ee6589fb765acb441e9 in the latest release.

**Comment by polaroidkidd** [comment]
Issue seems to be resolved.
